{
  "Header": {
    "Original": "CVE-2017-15288 (The compilation daemon in Scala before 2.10.7, 2.11.x before 2.11.12,  ...)",
    "Line": 379494,
    "ID": "CVE-2017-15288",
    "Description": "(The compilation daemon in Scala before 2.10.7, 2.11.x before 2.11.12,  ...)"
  },
  "Annotations": [
    {
      "Original": "- scala 2.11.12-1 (unimportant)",
      "Line": 379495,
      "Type": "package",
      "Package": "scala",
      "Kind": "fixed",
      "Version": "2.11.12-1",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: http://scala-lang.org/news/security-update-nov17.html",
      "Line": 379496,
      "Type": "NOTE",
      "Description": "http://scala-lang.org/news/security-update-nov17.html"
    },
    {
      "Original": "NOTE: For 2.11.x: https://github.com/scala/scala/pull/6108",
      "Line": 379497,
      "Type": "NOTE",
      "Description": "For 2.11.x: https://github.com/scala/scala/pull/6108"
    },
    {
      "Original": "NOTE: For 2.12.x: https://github.com/scala/scala/pull/6120",
      "Line": 379498,
      "Type": "NOTE",
      "Description": "For 2.12.x: https://github.com/scala/scala/pull/6120"
    },
    {
      "Original": "NOTE: For 2.10.x: https://github.com/scala/scala/pull/6128",
      "Line": 379499,
      "Type": "NOTE",
      "Description": "For 2.10.x: https://github.com/scala/scala/pull/6128"
    },
    {
      "Original": "NOTE: Neutralised by kernel hardening",
      "Line": 379500,
      "Type": "NOTE",
      "Description": "Neutralised by kernel hardening"
    }
  ]
}