{
  "Header": {
    "Original": "CVE-2020-14332 (A flaw was found in the Ansible Engine when using module_args. Tasks e ...)",
    "Line": 226846,
    "ID": "CVE-2020-14332",
    "Description": "(A flaw was found in the Ansible Engine when using module_args. Tasks e ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4950-1}",
      "Line": 226847,
      "Type": "xref",
      "Bugs": [
        "DSA-4950-1"
      ]
    },
    {
      "Original": "- ansible 2.9.13+dfsg-1 (bug #966672)",
      "Line": 226848,
      "Type": "package",
      "Package": "ansible",
      "Kind": "fixed",
      "Version": "2.9.13+dfsg-1",
      "BugNo": 966672
    },
    {
      "Original": "[stretch] - ansible \u003cend-of-life\u003e (EOL'd for stretch)",
      "Line": 226849,
      "Type": "package",
      "Release": "stretch",
      "Package": "ansible",
      "Kind": "end-of-life",
      "Description": "EOL'd for stretch"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=1857805",
      "Line": 226850,
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=1857805"
    },
    {
      "Original": "NOTE: https://github.com/ansible/ansible/pull/71033",
      "Line": 226851,
      "Type": "NOTE",
      "Description": "https://github.com/ansible/ansible/pull/71033"
    },
    {
      "Original": "NOTE: https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a (v2.9.12)",
      "Line": 226852,
      "Type": "NOTE",
      "Description": "https://github.com/ansible/ansible/commit/6cae9a4b168df776bf82deb04b2c62e00c38b49a (v2.9.12)"
    }
  ]
}