{
  "Header": {
    "Original": "CVE-2020-27619 (In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK  ...)",
    "Line": 192342,
    "ID": "CVE-2020-27619",
    "Description": "(In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK  ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.9 \u003cremoved\u003e (unimportant)",
      "Line": 192343,
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed",
      "Severity": "unimportant"
    },
    {
      "Original": "- python3.8 \u003cremoved\u003e (unimportant)",
      "Line": 192344,
      "Type": "package",
      "Package": "python3.8",
      "Kind": "removed",
      "Severity": "unimportant"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e (unimportant)",
      "Line": 192345,
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed",
      "Severity": "unimportant"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e (unimportant)",
      "Line": 192346,
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://python-security.readthedocs.io/vuln/cjk-codec-download-eval.html",
      "Line": 192347,
      "Type": "NOTE",
      "Description": "https://python-security.readthedocs.io/vuln/cjk-codec-download-eval.html"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/2ef5caa58febc8968e670e39e3d37cf8eef3cab8 (master)",
      "Line": 192348,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/2ef5caa58febc8968e670e39e3d37cf8eef3cab8 (master)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/a8bf44d04915f7366d9f8dfbf84822ac37a4bab3 (master)",
      "Line": 192349,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/a8bf44d04915f7366d9f8dfbf84822ac37a4bab3 (master)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/b664a1df4ee71d3760ab937653b10997081b1794 (3.9)",
      "Line": 192350,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/b664a1df4ee71d3760ab937653b10997081b1794 (3.9)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/6c6c256df3636ff6f6136820afaefa5a10a3ac33 (3.8)",
      "Line": 192351,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/6c6c256df3636ff6f6136820afaefa5a10a3ac33 (3.8)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/43e523103886af66d6c27cd72431b5d9d14cd2a9 (3.7)",
      "Line": 192352,
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/43e523103886af66d6c27cd72431b5d9d14cd2a9 (3.7)"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue41944",
      "Line": 192353,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue41944"
    },
    {
      "Original": "NOTE: Only affects the testsuite",
      "Line": 192354,
      "Type": "NOTE",
      "Description": "Only affects the testsuite"
    }
  ]
}