{
  "Header": {
    "Original": "CVE-2017-2640 (An out-of-bounds write flaw was found in the way Pidgin before 2.12.0  ...)",
    "Line": 422905,
    "ID": "CVE-2017-2640",
    "Description": "(An out-of-bounds write flaw was found in the way Pidgin before 2.12.0  ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-3806-1 DLA-853-1}",
      "Line": 422906,
      "Type": "xref",
      "Bugs": [
        "DSA-3806-1",
        "DLA-853-1"
      ]
    },
    {
      "Original": "- pidgin 2.12.0-1 (bug #859159)",
      "Line": 422907,
      "Type": "package",
      "Package": "pidgin",
      "Kind": "fixed",
      "Version": "2.12.0-1",
      "BugNo": 859159
    },
    {
      "Original": "NOTE: https://www.pidgin.im/news/security/?id=109",
      "Line": 422908,
      "Type": "NOTE",
      "Description": "https://www.pidgin.im/news/security/?id=109"
    },
    {
      "Original": "NOTE: https://bitbucket.org/pidgin/main/commits/b2fc9e774cb9",
      "Line": 422909,
      "Type": "NOTE",
      "Description": "https://bitbucket.org/pidgin/main/commits/b2fc9e774cb9"
    }
  ]
}