{
  "Header": {
    "Original": "CVE-2020-14318 (A flaw was found in the way samba handled file and directory permissio ...)",
    "Line": 228206,
    "ID": "CVE-2020-14318",
    "Description": "(A flaw was found in the way samba handled file and directory permissio ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2463-1}",
      "Line": 228207,
      "Type": "xref",
      "Bugs": [
        "DLA-2463-1"
      ]
    },
    {
      "Original": "[experimental] - samba 2:4.13.2+dfsg-1",
      "Line": 228208,
      "Type": "package",
      "Release": "experimental",
      "Package": "samba",
      "Kind": "fixed",
      "Version": "2:4.13.2+dfsg-1"
    },
    {
      "Original": "- samba 2:4.13.2+dfsg-2 (bug #973400)",
      "Line": 228209,
      "Type": "package",
      "Package": "samba",
      "Kind": "fixed",
      "Version": "2:4.13.2+dfsg-2",
      "BugNo": 973400
    },
    {
      "Original": "[buster] - samba \u003cno-dsa\u003e (Minor issue)",
      "Line": 228210,
      "Type": "package",
      "Release": "buster",
      "Package": "samba",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://www.samba.org/samba/security/CVE-2020-14318.html",
      "Line": 228211,
      "Type": "NOTE",
      "Description": "https://www.samba.org/samba/security/CVE-2020-14318.html"
    },
    {
      "Original": "NOTE: https://bugzilla.samba.org/show_bug.cgi?id=14434",
      "Line": 228212,
      "Type": "NOTE",
      "Description": "https://bugzilla.samba.org/show_bug.cgi?id=14434"
    }
  ]
}