{
  "Header": {
    "Original": "CVE-2017-16790 (An issue was discovered in Symfony before 2.7.38, 2.8.31, 3.2.14, 3.3. ...)",
    "Line": 378432,
    "ID": "CVE-2017-16790",
    "Description": "(An issue was discovered in Symfony before 2.7.38, 2.8.31, 3.2.14, 3.3. ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4262-1}",
      "Line": 378433,
      "Type": "xref",
      "Bugs": [
        "DSA-4262-1"
      ]
    },
    {
      "Original": "- symfony 3.4.0+dfsg-1",
      "Line": 378434,
      "Type": "package",
      "Package": "symfony",
      "Kind": "fixed",
      "Version": "3.4.0+dfsg-1"
    },
    {
      "Original": "[jessie] - symfony \u003cnot-affected\u003e (vulnerable code introduced in 2.4.*)",
      "Line": 378435,
      "Type": "package",
      "Release": "jessie",
      "Package": "symfony",
      "Kind": "not-affected",
      "Description": "vulnerable code introduced in 2.4.*"
    },
    {
      "Original": "NOTE: https://symfony.com/blog/cve-2017-16790-ensure-that-submitted-data-are-uploaded-files",
      "Line": 378436,
      "Type": "NOTE",
      "Description": "https://symfony.com/blog/cve-2017-16790-ensure-that-submitted-data-are-uploaded-files"
    },
    {
      "Original": "NOTE: https://github.com/symfony/symfony/pull/24993",
      "Line": 378437,
      "Type": "NOTE",
      "Description": "https://github.com/symfony/symfony/pull/24993"
    }
  ]
}