{
  "Header": {
    "Original": "CVE-2014-0480 (The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x  ...)",
    "Line": 506946,
    "ID": "CVE-2014-0480",
    "Description": "(The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x  ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-3010-1 DLA-65-1}",
      "Line": 506947,
      "Type": "xref",
      "Bugs": [
        "DSA-3010-1",
        "DLA-65-1"
      ]
    },
    {
      "Original": "- python-django 1.6.6-1",
      "Line": 506948,
      "Type": "package",
      "Package": "python-django",
      "Kind": "fixed",
      "Version": "1.6.6-1"
    }
  ]
}