{
  "Header": {
    "Original": "CVE-2019-17358 (Cacti through 1.2.7 is affected by multiple instances of lib/functions ...)",
    "Line": 271084,
    "ID": "CVE-2019-17358",
    "Description": "(Cacti through 1.2.7 is affected by multiple instances of lib/functions ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4604-1 DLA-2032-1}",
      "Line": 271085,
      "Type": "xref",
      "Bugs": [
        "DSA-4604-1",
        "DLA-2032-1"
      ]
    },
    {
      "Original": "- cacti 1.2.8+ds1-1 (bug #947375)",
      "Line": 271086,
      "Type": "package",
      "Package": "cacti",
      "Kind": "fixed",
      "Version": "1.2.8+ds1-1",
      "BugNo": 947375
    },
    {
      "Original": "NOTE: https://github.com/Cacti/cacti/issues/3026",
      "Line": 271087,
      "Type": "NOTE",
      "Description": "https://github.com/Cacti/cacti/issues/3026"
    },
    {
      "Original": "NOTE: https://github.com/Cacti/cacti/commit/adf221344359f5b02b8aed43dfb6b33ae5d708c8",
      "Line": 271088,
      "Type": "NOTE",
      "Description": "https://github.com/Cacti/cacti/commit/adf221344359f5b02b8aed43dfb6b33ae5d708c8"
    }
  ]
}