{
  "Header": {
    "Original": "CVE-2015-7699 (The files_external app in ownCloud Server before 7.0.9, 8.0.x before 8 ...)",
    "Line": 460946,
    "ID": "CVE-2015-7699",
    "Description": "(The files_external app in ownCloud Server before 7.0.9, 8.0.x before 8 ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-3373-1}",
      "Line": 460947,
      "Type": "xref",
      "Bugs": [
        "DSA-3373-1"
      ]
    },
    {
      "Original": "- owncloud 7.0.9~dfsg-1",
      "Line": 460948,
      "Type": "package",
      "Package": "owncloud",
      "Kind": "fixed",
      "Version": "7.0.9~dfsg-1"
    },
    {
      "Original": "NOTE: https://owncloud.org/security/advisory/?id=oc-sa-2015-018",
      "Line": 460949,
      "Type": "NOTE",
      "Description": "https://owncloud.org/security/advisory/?id=oc-sa-2015-018"
    },
    {
      "Original": "NOTE: https://github.com/owncloud/core/commit/b05e178bbf884b120d1106e6a28f35aa50d6d06f",
      "Line": 460950,
      "Type": "NOTE",
      "Description": "https://github.com/owncloud/core/commit/b05e178bbf884b120d1106e6a28f35aa50d6d06f"
    }
  ]
}