{
  "Header": {
    "Original": "CVE-2015-5145 (validators.URLValidator in Django 1.8.x before 1.8.3 allows remote att ...)",
    "Line": 466611,
    "ID": "CVE-2015-5145",
    "Description": "(validators.URLValidator in Django 1.8.x before 1.8.3 allows remote att ...)"
  },
  "Annotations": [
    {
      "Original": "- python-django \u003cnot-affected\u003e (Vulnerable code not present)",
      "Line": 466612,
      "Type": "package",
      "Package": "python-django",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "NOTE: https://www.djangoproject.com/weblog/2015/jul/08/security-releases/",
      "Line": 466613,
      "Type": "NOTE",
      "Description": "https://www.djangoproject.com/weblog/2015/jul/08/security-releases/"
    }
  ]
}