{
  "Header": {
    "Original": "CVE-2017-14501 (An out-of-bounds read flaw exists in parse_file_info in archive_read_s ...)",
    "Line": 382368,
    "ID": "CVE-2017-14501",
    "Description": "(An out-of-bounds read flaw exists in parse_file_info in archive_read_s ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4360-1 DLA-1600-1}",
      "Line": 382369,
      "Type": "xref",
      "Bugs": [
        "DSA-4360-1",
        "DLA-1600-1"
      ]
    },
    {
      "Original": "- libarchive 3.2.2-4.2 (bug #875966)",
      "Line": 382370,
      "Type": "package",
      "Package": "libarchive",
      "Kind": "fixed",
      "Version": "3.2.2-4.2",
      "BugNo": 875966
    },
    {
      "Original": "[wheezy] - libarchive \u003cno-dsa\u003e (Minor issue)",
      "Line": 382371,
      "Type": "package",
      "Release": "wheezy",
      "Package": "libarchive",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/libarchive/libarchive/issues/949",
      "Line": 382372,
      "Type": "NOTE",
      "Description": "https://github.com/libarchive/libarchive/issues/949"
    },
    {
      "Original": "NOTE: https://github.com/libarchive/libarchive/commit/f9569c086ff29259c73790db9cbf39fe8fb9d862",
      "Line": 382373,
      "Type": "NOTE",
      "Description": "https://github.com/libarchive/libarchive/commit/f9569c086ff29259c73790db9cbf39fe8fb9d862"
    }
  ]
}